### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by kaanyagci** [Makepad-fr/playgrid#5]
# The goal for `v1.0.0`

- Codebase should be divided into subprojects following mono repo.
- Monorepo should contain the following packages 
    - `server`: a public npm package that contains the code to launch a `PlaywrightServer`
    - `daemon`: a public npm package that contains the code to create a `PlaygridNode`
    - `commons`: a public npm package contains all code used both by `server` and `daemon` library packages
    - `web-app`:  the complete web application on production
    - `daemon-app`: An Electron app that connects to the Playgrid Network.
    - Exceptionally, the repository will contain the following packages `@makepad/eslint-config` and `makepad/tsconfig`
- README should be updated:
   - At the root level, the README should describe the project and the project structure
   - Under each project, there should be a README file explaining what that package does
- `@playgrid/server` and `@playgrid/daemon` packages should be completed. The server should also contain the endpoint to authenticate the connected client before letting them generate a token
- A base CLI-like application should be implemented for `@playgrid/daemon-app` and `@playgrid/web-app`  for the first production version.
   - For authentication, users should have two different options. One is to generate a one-time token that is only available once and invalidates once the connection is closed.  The other is a permanent token that should have an expiration date.
   - For the daemon, there should be an CLI that could be run on a RaspberryPi which can only start a given number of playwright servers with a given configuration

**Comment by kaanyagci** [comment]
## Update
- Codebase is refactored to a mono repo using `turborepo`
- `changeset` library added to manage versions 
- existing GitHub Actions workflows commented out as they are not designed for a mono repo

## TODOs:
- [ ] Think about a GitHub action that can handle versions in a mono repo configuration
- [ ] The socket for the daemon web socket server should be a part of the server configuration
- [ ] Start moving the part of the code that creates a `BrowserServer` to the `@playgrid/daemon` project and connect using websocket to the created Websocket server created in server for daemons
- [ ] Authenticate with the websocket server
- [ ] All messages should have type {command: '', data: string}
- [ ] Forward all messages to the playwright server by extracting data for a certain action
- [ ] When forwarding back playwright messages to the websocket server, add another command type to identify
- [ ] Implement following changes on the `@playgrid/server` project too.
